site_name: Quantman
theme:
  name: material
  favicon: assets/favicon.png
nav:
  - Welcome: "index.md"
  - Live Execution: "liveExecution.md"
  - Quant Creation: "quantCreation.md"
  - Indicators: "indicators.md"
  - Signals: "signals.md"
  - Transaction: "transaction.md"
  - BackTest Result: "backtestResult.md"
  - "Recent/Active Transactions Panel": "transactionPanel.md"
  - "Plans/Addon/Quota": "plansAndQuota.md"
copyright: Copyright © 2021, Quantman. All rights reserved.
extra:
  generator: false
  social: 
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/quantman1
  - icon: fontawesome/brands/facebook
    link: https://www.facebook.com/quant.man.16/
markdown_extensions:
  - attr_list
  - md_in_html
